version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://backend:8080
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env
    command: sh -c "
      if [ ! -f .env ]; then
        if [ -f .env.example ]; then
          cp .env.example .env;
          echo '.env file created from .env.example';
        else
          echo 'No .env or .env.example file found';
          exit 1;
        fi;
      else
        echo '.env file already exists';
      fi;
      ./main"
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgre_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-customer_dashboard}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: